function asynchVect = importAsychVector(filename)
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: E:\AYBEK\projet_EEG\Natacha_EEG_Project_2023\data\pilot3\asynchVect1.txt
%
% Auto-generated by MATLAB on 04-May-2023 12:06:34


%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
asynchVect = readtable(filename, opts);

%% Convert to output type
asynchVect = table2array(asynchVect);

%% Clear temporary variables
clear opts