function logfile = importLogfileRpeakDetection(filename, dataLines)
%IMPORTFILE Import data from a text file
%  logfile = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a cell array.
%
%  logfile = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  logfile = importfile("E:\AYBEK\projet_EEG\Natacha_EEG_Project_2023\data\pilot2\logfile_Pilot2.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Apr-2023 12:54:50

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Header", "Values", "Text"];
opts.VariableTypes = ["char", "double", "char"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Header", "Text"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Header", "Text"], "EmptyFieldRule", "auto");

% Import the data
logfile = readtable(filename, opts);

%% Convert to output type
logfile = table2cell(logfile);
numIdx = cellfun(@(x) ~isnan(str2double(x)), logfile);
logfile(numIdx) = cellfun(@(x) {str2double(x)}, logfile(numIdx));
end